### ISSUE TITLE
After added to cart, varnish doesn't cache anymore

### ISSUE THREAD

**Issue by thomasb0123** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#55]

**Comment by PHOENIX-MEDIA** [comment]
This is not a bug, it is an intended behavior. The same is true for a customer login.
The reason is that several page elements need to rendered individually, so serving cached pages would show wrong results (e.g. empty mini cart).

Please buy our PageCache powered by Varnish Enterprise Edition which can solve that issue using ESI blocks for dynamic content.
